# Generated by Django 3.2.5 on 2024-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='image_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
